name: Site CI (using Jekyll)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Run Jekyll
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        dgraziotin/jekyll-imagemagick6:stable /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future --trace" \
        --env JEKYLL_ENV=production 

    # Zip build output
    - name: Zip Website output
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
      uses: montudor/action-zip@v1.0.0
      with:
        # See montudor/action-zip README.md for more info
        args: zip -qq -r site.zip _site

    # Upload built zip to artefacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: website-src
        path: site.zip

    # Upload website to FTP server
    # See: https://github.com/ahdbilal/FTP-Upload-Action
    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USR }}
        FTP_PASSWORD: ${{ secrets.FTP_PWD }}
        LOCAL_DIR: _site/
        REMOTE_DIR: web/
        ARGS: --delete --parallel=20 --transfer-all
